name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy

    steps:
    - uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: humble

    - uses: actions/checkout@v3

    - name: Install serial driver
      run: sudo apt update && sudo apt install -y ros-humble-serial-driver

    - name: Configure CMake
      shell: bash
      run: source /opt/ros/humble/setup.bash && cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      shell: bash
      run: source /opt/ros/humble/setup.bash && cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
